version: '2'
services:
  # you can enable
  # db:
  #   container_name: rdb
  #   image: postgres:9.4.6
  #   environment:
  #     - POSTGRES_USER=django
  #     - POSTGRES_PASSWORD=django
  #   ports:
  #     - "5432:5432"
  web:
    container_name: web
    build:
      context: .
    image: nberserk/django-angular2-seed
    command: ["supervisord", "-n"]
    ports:
      - "80:80"
    # links:
    #   - rdb

